#!/bin/bash
trap 'kill $(jobs -p)' EXIT
#initialize cameras (0 = above box, 1 = maze, 2 = in box)
(oat frameserve gige raw -c config.toml cam1) &

#undistort frames
(oat framefilt undistort raw und -c config.toml maze) &

#apply mask
(oat framefilt mask und msk -c config.toml mask) &

#prepare frames for object detection
(oat framefilt mog msk filt) &

#perform object detection
(oat posidet hsv filt pos -c config.toml hsv-config) &

#decorate undistorted frames with position data
(oat decorate und dec -p pos) &

#network position
(oat posisock rep pos -e tcp\:\/\/192.168.2.13\:5555) &

#view video stream
(oat view dec) &

#save video stream
(oat record -d -n maze -s dec -p pos)
