#!/bin/bash
trap 'kill $(jobs -p)' EXIT
#initialize cameras (0 = above box, 1 = maze, 2 = in box)
(oat frameserve gige raw1 -c config.toml cam1) &

#undistort frames
(oat framefilt undistort raw1 und -c config.toml maze) &

#apply mask
(oat framefilt mask und msk -c config.toml mask) &

#prepare frames for object detection
(oat framefilt mog msk filt1) &

#perform object detection
(oat posidet hsv filt1 pos1 --tune) &

#decorate original frames with position data
(oat decorate und dec1 -p pos1) &

#view video stream
(oat view dec1)

